### ISSUE TITLE
use of deprecated function of base64 module

### ISSUE THREAD

**Issue by andyxning** [iambocai/falcon-monit-scripts#4]
the function `encodestring` has been deprecated, and it is not convenient to use it as it will always contain an extra tailing `\n`. So, just use the `b64encode` function.

Original:

```
base64string = base64.encodestring('guest:guest').replace('\n', '')
```

New:

```
base64string = base64.b64encode('guest:guest')
```

**Comment by iambocai** [comment]
resolved

**Comment by andyxning** [comment]
@iambocai  It may be wrong in the new commit.
It should be `base64.b64encode` instead of `base64.encodestring`

**Comment by andyxning** [comment]
I think you can have a look at it. :)
