### ISSUE TITLE
redis执行命令需要稍改下当redis有密码的时候

### ISSUE THREAD

**Issue by zzlyzq** [iambocai/falcon-monit-scripts#9]
```
def __init__(self,  port='6379', passwd=None, host='127.0.0.1'):
    self._cmd = '%s -h %s -p %s info' % (self._redis_cli, host, port)
    if passwd not in ['', None]:
```

self._cmd = "%s -a %s" % (self._cmd, passwd ) // 如果带有密码的话，不能直接把-a password放到命令中，需要把info 放在最后。

**Comment by zzlyzq** [comment]
`if passwd not in ['', None]:
            #self._cmd = "%s -a %s" % (self._cmd, passwd )
        self._cmd = '%s -h %s -p %s -a %s info' % (self._redis_cli, host, port, passwd)`

**Comment by iambocai** [comment]
commit已合并，感谢贡献
